name = nh_oz_npc
description = Oz — An ethereal and invisible being that responds to chat. A chat NPC with keyword-based intent detection, dynamic emotional state, and performs some functions.
min_minetest_version = 5.15
