name = nh_mob
description = Adiciona mobs para o mod Mobs Redo que andam em direções aleatórias e alguns pulam ao detectar jogadores, demonstrando alegria (inspirado no estilo antigo do Minecraft).
author = Dante, CookieUkw
version = 1.0.0
date = 2025-02-28
depends = nh_nodes, mobs
